// Package tooling handles 'fe add <tool>' — wiring up LSP and editor configs.
package tooling

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/flushwhy/fe/internal/ui"
)

type Tool string

const (
	ToolClangd Tool = "clangd"
	ToolOLS    Tool = "ols"
	ToolZLS    Tool = "zls"
	ToolGopls  Tool = "gopls"
)

var SupportedTools = []Tool{ToolClangd, ToolOLS, ToolZLS, ToolGopls}

func Add(tool Tool) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("could not get working directory: %w", err)
	}

	ui.Title("Adding %s to %s", tool, filepath.Base(cwd))

	start := time.Now()

	switch tool {
	case ToolClangd:
		err = addClangd(cwd)
	case ToolOLS:
		err = addOLS(cwd)
	case ToolZLS:
		err = addZLS(cwd)
	case ToolGopls:
		err = addGopls(cwd)
	default:
		return fmt.Errorf("unsupported tool %q — supported: %s", tool, supportedList())
	}

	if err != nil {
		return err
	}

	ui.Elapsed(start)
	return nil
}

// ── clangd ────────────────────────────────────────────────────────────────────

func addClangd(root string) error {
	var compileCommandsDir string

	err := ui.RunSpinner("Detecting build system", func() error {
		compileCommandsDir = findCompileCommandsDir(root)
		return nil
	})
	if err != nil {
		return err
	}

	ui.Dim("CompilationDatabase → %s", compileCommandsDir)

	err = ui.RunSpinner("Writing .clangd config", func() error {
		cfg := buildClangdConfig(root, compileCommandsDir)
		return writeFileWithBackup(filepath.Join(root, ".clangd"), []byte(cfg))
	})
	if err != nil {
		return err
	}

	err = ui.RunSpinner("Ensuring compile_commands.json exists", func() error {
		ccPath := filepath.Join(compileCommandsDir, "compile_commands.json")
		if _, err := os.Stat(ccPath); os.IsNotExist(err) {
			if err := os.MkdirAll(compileCommandsDir, os.ModePerm); err != nil {
				return err
			}
			return os.WriteFile(ccPath, []byte("[]\n"), 0644)
		}
		return nil
	})
	if err != nil {
		return err
	}

	fmt.Println()
	printClangdNextSteps(root)
	return nil
}

func findCompileCommandsDir(root string) string {
	for _, buildDir := range []string{"build", "cmake-build-debug", "cmake-build-release"} {
		cc := filepath.Join(root, buildDir, "compile_commands.json")
		if _, err := os.Stat(cc); err == nil {
			return filepath.Join(root, buildDir)
		}
	}
	if _, err := os.Stat(filepath.Join(root, "CMakeLists.txt")); err == nil {
		return filepath.Join(root, "build")
	}
	if _, err := os.Stat(filepath.Join(root, "compile_commands.json")); err == nil {
		return root
	}
	return root
}

func buildClangdConfig(root, compileCommandsDir string) string {
	rel, err := filepath.Rel(root, compileCommandsDir)
	if err != nil {
		rel = compileCommandsDir
	}

	var b strings.Builder
	b.WriteString("# Generated by fe — https://github.com/flushwhy/fe\n")
	b.WriteString("# Re-run 'fe add clangd' if your project structure changes.\n\n")
	b.WriteString("CompileFlags:\n")
	if rel != "." {
		fmt.Fprintf(&b, "  CompilationDatabase: %s\n", rel)
	}
	b.WriteString("  Add:\n")
	b.WriteString("    - \"-Wall\"\n")
	b.WriteString("    - \"-Wextra\"\n\n")
	b.WriteString("Diagnostics:\n")
	b.WriteString("  UnusedIncludes: Strict\n\n")
	b.WriteString("InlayHints:\n")
	b.WriteString("  Enabled: true\n")
	b.WriteString("  ParameterNames: true\n")
	b.WriteString("  DeducedTypes: true\n\n")
	b.WriteString("Hover:\n")
	b.WriteString("  ShowAKA: true\n")
	return b.String()
}

func printClangdNextSteps(root string) {
	hasCMake := fileExists(filepath.Join(root, "CMakeLists.txt"))
	hasMakefile := fileExists(filepath.Join(root, "Makefile"))

	if hasCMake {
		ui.Hint(
			"cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
			"cmake --build build",
			"# clangd will index automatically once compile_commands.json is populated",
		)
	} else if hasMakefile {
		ui.Hint(
			"bear -- make          — generates compile_commands.json",
			"# clangd will index automatically once that's done",
		)
	} else {
		ui.Hint(
			"bear -- <your build command>   — generates compile_commands.json",
			"# or: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
		)
	}
}

// ── OLS ───────────────────────────────────────────────────────────────────────

func addOLS(root string) error {
	olsPath := filepath.Join(root, "ols.json")

	if _, err := os.Stat(olsPath); err == nil {
		return ui.RunSpinner("Patching existing ols.json", func() error {
			return patchOLS(olsPath)
		})
	}

	return ui.RunSpinner("Writing ols.json", func() error {
		pkgName := filepath.Base(root)
		cfg := map[string]interface{}{
			"$schema":                "https://raw.githubusercontent.com/DanielGavin/ols/master/misc/ols.schema.json",
			"enable_semantic_tokens": false,
			"enable_document_hover":  true,
			"enable_snippets":        true,
			"enable_format":          true,
			"enable_inlay_hints":     true,
			"collections": []map[string]string{
				{"name": pkgName, "path": "src"},
			},
		}
		data, err := json.MarshalIndent(cfg, "", "  ")
		if err != nil {
			return err
		}
		if err := os.WriteFile(olsPath, append(data, '\n'), 0644); err != nil {
			return fmt.Errorf("writing ols.json: %w", err)
		}
		return nil
	})
}

func patchOLS(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var cfg map[string]interface{}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return fmt.Errorf("ols.json is not valid JSON: %w", err)
	}
	changed := false
	if _, ok := cfg["enable_inlay_hints"]; !ok {
		cfg["enable_inlay_hints"] = true
		changed = true
	}
	if _, ok := cfg["enable_document_hover"]; !ok {
		cfg["enable_document_hover"] = true
		changed = true
	}
	if !changed {
		return nil
	}
	out, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(out, '\n'), 0644)
}

// ── ZLS ───────────────────────────────────────────────────────────────────────

func addZLS(root string) error {
	zlsPath := filepath.Join(root, "zls.json")
	if _, err := os.Stat(zlsPath); err == nil {
		ui.OK("zls.json already exists — nothing to change")
		return nil
	}
	return ui.RunSpinner("Writing zls.json", func() error {
		cfg := map[string]interface{}{
			"enable_snippets":                      true,
			"enable_argument_placeholders":         true,
			"enable_build_on_save":                 false,
			"inlay_hints_show_variable_type_hints": true,
			"inlay_hints_show_parameter_name":      true,
			"inlay_hints_show_builtin":             true,
			"inlay_hints_exclude_single_argument":  true,
			"warn_style":                           false,
			"highlight_global_var_declarations":    false,
		}
		data, err := json.MarshalIndent(cfg, "", "  ")
		if err != nil {
			return err
		}
		return os.WriteFile(zlsPath, append(data, '\n'), 0644)
	})
}

// ── gopls ─────────────────────────────────────────────────────────────────────

func addGopls(root string) error {
	goplsPath := filepath.Join(root, ".gopls.yaml")
	if _, err := os.Stat(goplsPath); err == nil {
		ui.OK(".gopls.yaml already exists — nothing to change")
		return nil
	}
	return ui.RunSpinner("Writing .gopls.yaml", func() error {
		config := `# gopls workspace configuration — generated by fe
# https://github.com/golang/tools/blob/master/gopls/doc/settings.md

hints:
  assignVariableTypes: true
  compositeLiteralFields: true
  compositeLiteralTypes: true
  constantValues: true
  functionTypeParameters: true
  parameterNames: true
  rangeVariableTypes: true

formatting:
  gofumpt: false

ui:
  completion:
    usePlaceholders: true
  diagnostic:
    staticcheck: true
`
		return os.WriteFile(goplsPath, []byte(config), 0644)
	})
}

// ── helpers ───────────────────────────────────────────────────────────────────

func writeFileWithBackup(path string, content []byte) error {
	if _, err := os.Stat(path); err == nil {
		bak := path + ".bak"
		if err := os.Rename(path, bak); err != nil {
			return fmt.Errorf("backing up %s: %w", path, err)
		}
	}
	return os.WriteFile(path, content, 0644)
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func supportedList() string {
	names := make([]string, len(SupportedTools))
	for i, t := range SupportedTools {
		names[i] = string(t)
	}
	return strings.Join(names, ", ")
}
