name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: amd64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build binary
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/pngjoiner-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pngjoiner-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/pngjoiner-${{ matrix.goos }}-${{ matrix.goarch }}

  flatpak:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install flatpak tools
        run: sudo apt-get update && sudo apt-get install -y flatpak flatpak-builder
      - name: Build Flatpak (placeholder)
        run: echo "You need to add a flatpak manifest and build instructions here."
